flags:
  anime-rss: {pedantic: true}

extra-package-dbs: []

packages:
  - .

extra-deps:
  - acid-state-0.16.0
  - https://github.com/IxpertaSolutions/freer-effects/archive/39a7e62cc049d43d36ece4ac24ba19e545f0b726.zip

resolver: lts-16.7
